version: '3.8'

services:
  web:
    build: .
    container_name: Test_Web
    volumes:
      - .:/app
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql://fastapi_traefik:fastapi_traefik@db:5432/fastapi_traefik
    depends_on:
      - db_postgres
    entrypoint: ["uvicorn", "app:app", "--port", "8000", "--host", "0.0.0.0"]
  db_postgres:
    image: postgres:13-alpine
    container_name: DB_pg
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=fastapi_traefik
      - POSTGRES_PASSWORD=fastapi_traefik
      - POSTGRES_DB=fastapi_traefik

volumes:
  postgres_data:
