version: '3.8'

services:
  api:
    build: .
    container_name: api
    env_file:
      - .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - postgres
      - redis
    entrypoint: ["python3", "main.py"]


  postgres:
    image: postgres
    container_name: postgres
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}


  redis:
    image: redis:5
    container_name: redis
    env_file:
      - .env
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
     - ${REDIS_PORT}:${REDIS_PORT}


  pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin4_container
      env_file:
        - .env
      restart: always
      ports:
        - "5050:80"
      environment:
        PGADMIN_DEFAULT_EMAIL: raj@nola.com
        PGADMIN_DEFAULT_PASSWORD: admin
      volumes:
        - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data: